export const FETCH_ALL_DATA = "FETCH_ALL_DATA";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_FAILED = "PRODUCT_FAILED";

export const FETCH_SINGLE_PRODUCT_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST";
export const FETCH_SINGLE_PRODUCT_REQUEST_SUCCESS =
  "FETCH_SINGLE_PRODUCT_REQUEST_SUCCESS";
export const FETCH_SINGLE_PRODUCT_REQUEST_FAILURE =
  "FETCH_SINGLE_PRODUCT_REQUEST_FAILURE";
